### PR TITLE
Some site added

### PR DESCRIPTION
**Pull request by thezawad**
A few sites added to the list, will try to add some more again :-)

### CODE REVIEW

**Comment by aniruddha-adhikary** [comment]
thanks @thezawad !

**Comment by thezawad** [comment]
Welcome bro @aniruddha-adhikary , BTW when you are starting the coding of the plugin? and for which browser?

:-)

**Comment by aniruddha-adhikary** [comment]
It's coming for Firefox, Chrome, IE and Safari :smile:

**Comment by shawon922** [comment]
I added some links into the list one month ago. Can you please merge those ? @aniruddha-adhikary  bro.

**Pull request merged**
